kind = "mobile"
previewPath = "/"
title = "SocialApp"
version = "1.0.0"
id = "artifacts/social-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 26175

[services.development]
run = "pnpm --filter @workspace/social-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/social-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/social-app", "run", "serve" ]

[services.env]
PORT = "26175"
BASE_PATH = "/"
