uploads = []
outputs = []

[[generated]]
id = "buq7k7FbA3uW3_hXlVk2Y"
uri = "file://artifacts/social-app/assets/images/icon.png"
type = "image"
title = "social app icon"

[[generated]]
id = "Sud4nL72aSaOOGsH2CIme"
uri = "file://artifacts/social-app/assets/images/placeholder-post.png"
type = "image"
title = "post placeholder"

[[generated]]
id = "UqXPqJeTAx7KgetOsY6h5"
uri = "file://artifacts/social-app/assets/images/placeholder-avatar.png"
type = "image"
title = "avatar placeholder"
