name: social_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  google_mobile_ads: ^5.1.0
  rive: 0.13.15

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2
  go_router: ^17.2.3
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  firebase_remote_config: ^6.5.1
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.3.1
  image_picker: ^1.2.2
  pro_image_editor: ^12.4.4
  flutter_svg: ^2.3.0
  hugeicons: ^1.1.7
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  device_info_plus: ^13.1.0
  shorebird_code_push: ^2.0.2
  image: ^4.8.0
  path_provider: ^2.1.5
  http: ^1.6.0
  gal: ^2.3.2
  google_fonts: ^8.1.0
  any_link_preview: ^3.0.3
  material_symbols_icons: ^4.2928.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  json_serializable: ^6.11.2
  riverpod_generator: ^4.0.3

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/rive/
    - shorebird.yaml
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/MirandaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/MirandaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/MirandaSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/MirandaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/MirandaSans-Bold.ttf
          weight: 800
