import { useState } from "react";
import { Bell, Bookmark, ChevronLeft, Compass, Heart, Home, ImagePlus, Menu, MessageCircle, MoreHorizontal, Plus, Repeat2, Search, Send, Settings, Share2, UserRound, X } from "lucide-react";
import "./index.css";

type Page = "feed" | "search" | "notifications" | "messages" | "profile" | "settings";
type Post = { id:number; name:string; handle:string; time:string; avatar:string; text:string; image:string; likes:number; comments:number };
const posts: Post[] = [
  { id:1, name:"Maya Chen", handle:"@mayachen", time:"2h", avatar:"MC", text:"A quiet morning, a good cup of coffee, and a fresh perspective. Sometimes that’s all you need.", image:"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=85", likes:248, comments:32 },
  { id:2, name:"Arjun Das", handle:"@arjundas", time:"4h", avatar:"AD", text:"Building something that feels simple is harder than building something complex. Still learning every day.", image:"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=85", likes:186, comments:18 },
  { id:3, name:"Sofia Williams", handle:"@sofiaw", time:"6h", avatar:"SW", text:"The best ideas usually show up when you stop trying so hard to find them.", image:"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=85", likes:412, comments:46 },
];
function Avatar({ text, large=false }: {text:string; large?:boolean}) { return <span className={`avatar ${large ? "large" : ""}`}>{text}</span> }
function Login({ onLogin }:{onLogin:()=>void}) { const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); return <main className="login-screen"><img src="/assets/text-logo-dark.svg" className="login-logo" alt="Parallaxa"/><section className="login-form"><h1>Welcome back</h1><p>Sign in to continue to your account</p><label>Email Address<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Enter your email" type="email"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" type="password"/></label><button className="blue-button" disabled={!email || !password} onClick={onLogin}>Sign in</button><button className="link-button">Forgot password?</button><div className="or"><span/>or<span/></div><p className="signup">Don’t have an account? <button className="link-button">Create account</button></p></section></main> }
function AppBar({ page, openMenu, go }:{page:Page;openMenu:()=>void;go:(p:Page)=>void}) { return <header className="app-bar"><button className="plain-icon" onClick={openMenu} aria-label="Open menu"><Menu/></button><img src="/assets/text-logo-dark.svg" alt="Parallaxa"/><button className="plain-icon" onClick={()=>go("search")} aria-label="Search"><Search/></button></header> }
function Stories(){ return <section className="stories"><div className="story"><div className="story-ring add"><Plus/></div><span>Your story</span></div>{[["MC","Maya"],["AD","Arjun"],["SW","Sofia"],["NK","Nadia"],["JR","Jasper"]].map(([a,n])=><div className="story" key={a}><div className="story-ring"><Avatar text={a}/></div><span>{n}</span></div>)}</section> }
function PostCard({post}:{post:Post}) { const [liked,setLiked]=useState(false); const [saved,setSaved]=useState(false); return <article className="post-card"><div className="post-head"><Avatar text={post.avatar}/><div><b>{post.name}</b><small>{post.handle} · {post.time}</small></div><button className="plain-icon more" aria-label="More options"><MoreHorizontal/></button></div><p>{post.text}</p><img src={post.image} alt={`Post by ${post.name}`}/><div className="post-actions"><button className={liked?"liked":""} onClick={()=>setLiked(!liked)}><Heart fill={liked?"currentColor":"none"}/><span>{post.likes+(liked?1:0)}</span></button><button><MessageCircle/><span>{post.comments}</span></button><button><Repeat2/></button><button className={saved?"saved":""} onClick={()=>setSaved(!saved)}><Bookmark fill={saved?"currentColor":"none"}/></button><button><Share2/></button></div></article> }
function Feed(){ const [tab,setTab]=useState("For You"); return <main><div className="tabs">{["For You","Following","Trending"].map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?"active":""}>{t}</button>)}</div><Stories/><div className="composer"><Avatar text="PD"/><span>Share something with your community...</span><ImagePlus/></div>{posts.map(p=><PostCard key={p.id} post={p}/>)}</main> }
function PageView({page, go}:{page:Page;go:(p:Page)=>void}) { if(page==="feed") return <Feed/>; const labels:Record<Page,[string,string]>={search:["Explore","Discover people and ideas worth following."],notifications:["Notifications","You’re all caught up."],messages:["Messages","Your conversations will appear here."],profile:["Profile","Prasenjeet Das\n@prasenjeet"],settings:["Settings","Manage your Parallaxa preferences."],feed:["",""]}; return <section className="empty"><button className="back-button" onClick={()=>go("feed")}><ChevronLeft/> {labels[page][0]}</button><div className="empty-content">{page==="profile"?<Avatar text="PD" large/>:<Compass/>}<h1>{labels[page][0]}</h1><p>{labels[page][1]}</p></div></section> }
function Drawer({open,close,page,go}:{open:boolean;close:()=>void;page:Page;go:(p:Page)=>void}) { if(!open)return null; return <><div className="scrim" onClick={close}/><aside className="drawer"><div className="drawer-top"><img src="/assets/text-logo-dark.svg" alt="Parallaxa"/><button className="plain-icon" onClick={close}><X/></button></div><div className="drawer-user"><Avatar text="PD" large/><b>Prasenjeet Das</b><small>@prasenjeet</small></div>{[["feed","Home",Home],["search","Explore",Compass],["messages","Messages",MessageCircle],["notifications","Notifications",Bell],["profile","Profile",UserRound],["settings","Settings",Settings]].map(([id,label,Icon])=><button className={page===id?"selected":""} key={id as string} onClick={()=>{go(id as Page);close()}}>{<Icon as any/>}{label as string}</button>)}</aside></> }
function Nav({page,go}:{page:Page;go:(p:Page)=>void}) { return <nav className="bottom-nav">{[["feed","Home",Home],["search","Explore",Compass],["messages","Messages",MessageCircle],["notifications","Alerts",Bell],["profile","Profile",UserRound]].map(([id,label,Icon])=><button className={page===id?"selected":""} key={id as string} onClick={()=>go(id as Page)}><Icon as any/><small>{label as string}</small></button>)}</nav> }
export default function App(){ const [logged,setLogged]=useState(false); const [page,setPage]=useState<Page>("feed"); const [menu,setMenu]=useState(false); if(!logged)return <Login onLogin={()=>setLogged(true)}/>; return <div className="phone-shell"><AppBar page={page} openMenu={()=>setMenu(true)} go={setPage}/><Drawer open={menu} close={()=>setMenu(false)} page={page} go={setPage}/><PageView page={page} go={setPage}/><Nav page={page} go={setPage}/></div> }
